### ISSUE TITLE
Version 0.1.2 tells me it is 0.1.0 and that there is an update

### ISSUE THREAD

**Issue by tiborepcek** [ErikKalkoken/janice#1]
Hi Erik and thank you for your work!

I would like to report a bug on version 0.1.2. After I unzipped the EXE file and run it, it shows the "Update available" link bottom right. After I click the link and then the link to the GitHub releases page, I do not see newer version then 0.1.2.

Could you please help me with this issue, as I am not sure whether I am using the newest version.

See the screenshot below.

![image](https://github.com/user-attachments/assets/c4ae5f6c-9f9c-4aa6-876d-2470e549a979)

**Comment by ErikKalkoken** [comment]
Hey!

My apologizes for the confusion. I was just testing the release process, but have not officially released the app yet.
Nevertheless, the app is ready now. I still got a few small improvements on my list, but since there is already interest I am happy to make a proper first release now. Please bear with me, I am planning to make that release today.

**Comment by ErikKalkoken** [comment]
Alright, I made the first official release. Please check it out and let me know if that fixes your issue.

I would also be very interested for your feedback in general and please let me know if you encounter any other issues.

**Comment by tiborepcek** [comment]
Look perfect now! My 5 MB JSON file with 417 elements was loaded in a fraction of a second. Really great job!

**Comment by ErikKalkoken** [comment]
Thank you very much! I am glad you like the app.
I will close this issue now as it is solved. Please let me know if you encounter any other issues.
